/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    " for": "",
    "/MIN": "/分钟",
    "Bush": "灌木",
    "Can fully idle without dying, grows very slowly.": "可以完全闲置而不会死亡，生长非常缓慢。",
    "Fern": "蕨类",
    "Grass": "草",
    "Grow Leaves:": "长叶子：",
    "Grow Roots:": "长根系：",
    "Grows uncontrollably.": "不受控制地生长。",
    "Makes DNA with Flowers.  Unlocks the map needed to beat the game.": "用花制造 DNA。 解锁通关游戏所需的地图。",
    "Max": "最大",
    "Max Resource to Spend": "最大资源消耗",
    "Moss": "苔藓",
    "Mushroom": "蘑菇",
    "Open Menu": "打开菜单",
    "Requires direct attention early on, prone to aphids.": "需要早期直接关注，容易出现蚜虫。",
    "Root Rot from Fungus": "真菌引起的根部腐烂",
    "Select a Species, you can change at any time": "选择一个物种，您可以随时更改",
    "Spring": "春季",
    "Succulent": "多肉植物",
    "The desert is harsh and dangerous, be ready.": "沙漠严酷而危险，请做好准备。",
    "You are a Fern": "你是一株蕨类植物",
    "You need to enable JavaScript to run this app.": "您需要启用 JavaScript 才能运行此应用程序。",
    "Aphid Immunity": "蚜虫免疫",
    "Black market DNA.": "黑市DNA。",
    "Blackest Market DNA.  This will remove all leaves and roots.": "黑市DNA。 这将去除所有叶子和根。",
    "Bountiful Harvest": "丰收",
    "Buy": "购买",
    "Buy 100 DNA": "购买 100 个 DNA",
    "Buy and Sell Traits for Future Seeds Below:": "购买和出售未来种子的特征如下：",
    "Buy DNA": "购买DNA",
    "Clone Upgrade (All Species)": "克隆升级（所有物种）",
    "Coniferous": "针叶",
    "Cost:": "成本：",
    "Double Autumn Bonus": "双倍秋季奖励",
    "Double Spring Bonus": "双倍春季奖励",
    "Double Summer Bonus": "双倍夏季奖励",
    "Double the rate of genetic marker production": "遗传标记产生率加倍",
    "Ferns are immune to aphids": "蕨类植物对蚜虫免疫",
    "Increase base sugar production by 100%": "基础糖产量增加 100%",
    "Increase base sugar production by 50%": "基础糖产量增加 50%",
    "Increase manual sunlight absorption by 100%": "手动阳光吸收量增加100%",
    "Increase manual sunlight absorption by 50%": "手动阳光吸收量增加 50%",
    "Increase manual water absorption by 100%": "手动吸水率提高100%",
    "Increase manual water absorption by 50%": "手动吸水率提高50%",
    "Increase passive sunlight absorption efficiency by 20%": "被动式阳光吸收效率提高 20%",
    "Increase passive sunlight absorption efficiency by 40%": "被动式阳光吸收效率提高 40%",
    "Increase passive water absorption efficiency by 20%": "被动吸水效率提高20%",
    "Increase passive water absorption efficiency by 40%": "被动吸水效率提高40%",
    "Increase the root rot threshold by 100%": "根腐阈值提高 100%",
    "Mushroom Store:": "蘑菇商店：",
    "Nitrogen": "氮",
    "Nutrient Recycling": "养分回收",
    "Plant Seed": "植物种子",
    "Reduce the base sunlight to sugar ratio by 10%": "将基础阳光与糖的比例减少 10%",
    "Reduce the base sunlight to sugar ratio by 20%": "将基础阳光与糖的比例减少 20%",
    "Reduce the base water to sugar ratio by 10%": "将基础水与糖的比例降低 10%",
    "Reduce the base water to sugar ratio by 20%": "将基础水与糖的比例降低 20%",
    "Reduce Winter penalty by 50%": "冬季惩罚减少 50%",
    "Spring Bloom": "春暖花开",
    "Start with 1K extra roots and leaves.": "从 1K 额外的根和叶开始。",
    "Symboisis": "共生关系",
    "Total DNA counting all upgrades:": "所有升级的总计 DNA：",
    "Try some fertilizer, time will just fly by.": "尝试一些肥料，时间就会过得很快。",
    "Join Discord": "加入 Discord",
    "and": "和",
    "Cells Currently Completed:": "目前已完成的单元：",
    "Converts": "转换",
    "Difficulty:": "难度：",
    "Donate": "捐赠",
    "Grow Leaves": "长叶子",
    "Help": "帮助",
    "Import/Export Save": "导入/导出保存",
    "into": "为",
    "Leaves": "叶子",
    "Manual Save": "手动保存",
    "Map": "地图",
    "Next Season:": "下一季节：",
    "Pause": "暂停",
    "per second.": "每秒。",
    "Plant Details": "植物详情",
    "Plant History": "植物历史",
    "Play Time:": "游戏时长：",
    "Purge Save": "清除保存",
    "Roots": "根系",
    "Score:": "分数：",
    "Size": "尺寸",
    "Summer": "夏季",
    "Time Resources": "时间资源",
    "To Next Season": "到下个季节",
    "Total Cells Completed:": "已完成的单元总数：",
    "Turn off Sugar Production": "关闭糖生产",
    "Turn on Sugar Production": "开启糖生产",
    "Unlock through Berry Bush": "通过浆果灌木解锁",
    "Using Reserves": "使用储备",
    "Grow Max Leaves": "长最大叶子",
    "Grow Max Roots": "长最大根系",
    "Grow Roots": "长根系",
    "Turn on Genetic Marker Production": "打开遗传标记生成",
    "Turn off Genetic Marker Production": "关闭遗传标记生成",
    "- Higher rates produce Time Resources Faster! Current Bonus:": "- 费率越高，产生时间资源的速度就越快！ 当前奖励：",
    "Are you sure you want to plant a new seed,": "您确定要种下新种子吗？",
    "Berry Bush": "浆果灌木",
    "Cancel": "取消",
    "Choose the type of plant to evolve to:": "选择要进化的植物类型：",
    "Confirm": "确认",
    "DNA progress is unique to each plant type and will not be reset with plant resources. This action cannot be undone.": "DNA 进度对于每种植物类型都是独特的，并且不会随植物资源而重置。 此操作无法撤消。",
    "Evolve Plant?": "进化植物？",
    "Will start a new": "将会开始一个新的",
    "with the following traits:": "具有以下特征：",
    "- Grass is absurdly slow to get DNA on compared to any of the other plants, especially if you haven't moved on the map yet. That said if you don't mind waiting for days it will eventually get there, especially if you did Moss first. It's not actually required though.": "- 与任何其他植物相比，草获取 DNA 的速度慢得离谱，特别是如果你还没有在地图上移动的话。 也就是说，如果你不介意等待几天，它最终会到达那里，特别是如果你先做了莫斯。 但这实际上并不是必需的。",
    "- Base sugar production rate * (1 + .1 * size);": "- 基础糖产量*（1 + .1 *尺寸）；",
    "- Berry Bush cannot trade with the Mushroom at all.": "- 浆果灌木根本无法与蘑菇进行交易。",
    "- Berry Bush DNA comes from maturing flowers. The amount of Sugar and Water needed to reach maturity is reset every time the Berry Bush is replanted.": "- 浆果灌木 DNA 来自成熟的花朵。 每次重新种植浆果丛时，达到成熟所需的糖和水量都会重置。",
    "- Building up a massive stockpile of Time Boost is fundamental to unlocking the Time Vine, but you might not even want to worry about the Time Vine your first map cell.": "- 建立大量的时间加速储备是解锁时间藤的基础，但你可能甚至不想担心你的第一个地图单元的时间藤。",
    "- Column bonuses exponentially increase some of the associated values for each plant.": "- 列奖励成倍增加每个植物的一些相关值。",
    "- Earn points by creating 1 Billion sugar!": "- 通过创造 10 亿颗糖来赚取积分！",
    "- Fern can trade with the Mushroom for DNA or Time Boosts. This will cause Root Rot that can be removed by emptying water.": "- 蕨类植物可以与蘑菇交易 DNA 或时间增益。 这会导致根部腐烂，可以通过排空水来去除。",
    "- Fern will become infested with aphids at 1000 sugar. There is an immunity trait that can be had.": "- 蕨类植物在糖度达到 1000 时就会感染蚜虫。 有一种可以拥有的免疫力特征。",
    "- Grass can typically just be left idle and will grow on its own.": "- 草通常可以闲置并自行生长。",
    "- Grass grows uncontrollably and has the slowest DNA generation.": "- 草的生长不受控制，并且 DNA 生成速度最慢。",
    "- Grass trades leaves for DNA rather than sugar. This is very slow. The number of leaves required can be reset for 250 B sunlight.": "- 草用叶子换取 DNA 而不是糖。 这非常慢。 所需的叶子数量可以根据 250 B 阳光进行重置。",
    "- Leaves passively absorb sunlight.": "- 叶子被动地吸收阳光。",
    "- Maturity is equal to the square root of the sum of roots and leaves.": "- 成熟度等于根和叶之和的平方根。",
    "- Moss can trade sunlight for sugar if you unlock the Lichen.": "- 如果你解锁地衣，苔藓可以用阳光换取糖。",
    "- Moss cannot trade with the Mushroom until you unlock the Lichen trait.": "- 在您解锁地衣特征之前，苔藓无法与蘑菇进行交易。",
    "- Moss grows very slowly.": "- 苔藓生长得很慢。",
    "- Moss requires nearly no attention if you want to do it slow and get it out of the way.": "- 如果你想慢慢地进行并把它移开，那么莫斯几乎不需要任何关注。",
    "- Needles protect you from water but cost more to grow the higher your size. Your size is the square root of the sum of your roots and leaves.": "- 针可以保护你免受水侵害，但你的体型越大，成本就越高。 你的大小是你的根和叶子之和的平方根。",
    "- Once you have 1 of each Fulvic, Tannins, Silica, and Calcium, you can create a Time Seed with the Berry Bush.": "- 一旦您拥有黄腐酸、单宁酸、二氧化硅和钙各 1 种，您就可以用浆果丛制作时间种子。",
    "- Only the first Billion sugar counts towards your score PER plant.": "- 只有前十亿糖才计入您每株植物的得分。",
    "- Progress towards the Time Vine Components is passively generated by time boosting four of the plants.": "- 时间藤蔓组件的进展是通过时间提升四种植物被动产生的。",
    "- Replant often with new traits to reset the time it takes to mature the flowers.": "- 经常重新种植新的性状，以重置花朵成熟所需的时间。",
    "- Roots passively absorb water.": "- 根被动吸收水分。",
    "- Starting next to a Bush: Flower maturity threshold is multiplied by .4. Also 5X manual absorption on all plants.": "- 从灌木丛旁边开始：花朵成熟度阈值乘以 0.4。 所有植物的手动吸收也达到 5 倍。",
    "- Starting next to a completed Fern tile: +100 to roots and leaves.": "- 从已完成的蕨类植物块旁边开始：+100 根和叶。",
    "- Starting next to a completed Succulent tile: 2x sugar production.": "- 从已完成的多肉植物旁边开始：2x 糖产量。",
    "- Starting next to a Grass tile: All seasonal bonuses are doubled, including winter rates, which means they can become bonuses with enough. Also 3X Spread on all plants. Also 5X manual absorption on all plants.": "- 从草块旁边开始：所有季节性奖励都会加倍，包括冬季奖励，这意味着它们可以成为足够的奖励。 还 3X 传播到所有植物上。 所有植物的手动吸收也达到 5 倍。",
    "- Starting next to a Time Vine: Amplifies the time boost effect, 2X more.": "- 从时间藤旁边开始：将时间提升效果放大 2 倍。",
    "- Starting next to Moss: 20x water and sunlight passive absorption.": "- 从苔藓旁边开始：20 倍水和阳光被动吸收。",
    "- Sugar production increases with maturity. Excluding modifiers from seasons and traits the formula is:": "- 糖产量随着成熟而增加。 排除季节和特征的修饰因素，公式为：",
    "- Sunlight mixes with water to make sugar during photosynthesis.": "- 阳光与水混合，在光合作用过程中产生糖。",
    "- That said, they are the most active play style and require the most attention.": "- 也就是说，它们是最活跃的游戏风格并且需要最多的关注。",
    "- The Berry Bush Meta Upgrade unlocks the map, this is the only upgrade technically required to win the game though in practice that would be insane.": "- 浆果灌木元升级解锁地图，这是赢得游戏所需的唯一技术升级，但实际上这可能是疯狂的。",
    "- The Discord is a great place to get help and advice, and to report bugs.": "- Discord 是获取帮助和建议以及报告错误的好地方。",
    "- The Fern Meta Upgrade increases the number of Roots and Leaves new plants start with.": "- 蕨元升级增加了新植物开始时的根和叶的数量。",
    "- The game is much closer to being done than it ever has been, but it is still in development.": "- 游戏比以往任何时候都更接近完成，但仍在开发中。",
    "- The Grass Meta Upgrade grants base Auto Growth 100 for all plants.": "- 草元升级为所有植物提供基础自动生长 100。",
    "- The Lady Bug will offer protection from aphids when needed at a steep cost.": "- 瓢虫 可以在需要时提供针对蚜虫的保护，但代价高昂。",
    "- The Moss Meta Upgrade makes leaves water neutral and no longer lost to dehydration. There are advantages and disadvantages to this.": "- 苔藓元升级使叶子水份呈中性，不再因脱水而流失。 这样做有优点也有缺点。",
    "- The number of points you earn is equal to the current difficulty you are playing on.": "- 您获得的积分数量等于您当前玩的难度。",
    "- The Succulent is a desert plant that grows slowly at first but makes sugar at the fastest rate and can even trade sugar with the Mushroom for water.": "- 多肉植物是一种沙漠植物，一开始生长缓慢，但产生糖的速度最快，甚至可以与蘑菇用糖交换水。",
    "- The Succulent is potentially the most active play style and fastest growing Plant. Do not hesitate.": "- 多肉植物可能是最活跃的游戏风格和生长最快的植物。 不要犹豫。",
    "- The Succulent Meta Upgrade increases provides all non-Succulent plants with 10x Sugar production.": "- 多肉植物元升级增加了所有非多肉植物的糖产量 10 倍。",
    "- The Time Vine CANNOT produce": "- 时间藤无法生产",
    "- The Time Vine is a special plant that can be unlocked by time boosting.": "- 时间藤是一种特殊植物，可以通过时间提升来解锁。",
    "- The Time Vine starts with 10k": "- 时间藤从 10k 开始",
    "- Traits can be purchased for DNA.": "- 性状可以通过DNA购买。",
    "- Traits can be sold back for DNA at any time for full value. Traits DO NOT take effect until you plant a new plant.": "- 性状可以随时以全部价值出售以换取 DNA。 在您种植新植物之前，性状不会生效。",
    "- Water mixes with sunlight to make sugar, it also is consumed by leaves.": "- 水与阳光混合产生糖，它也被叶子消耗。",
    "- You can only plant one Time Vine per Time Seed, but all upgrades and": "- 每个时间种子只能种植一棵时间藤，但所有升级和",
    "- You can onnly change the difficulty while planting a new plant.": "- 你只能在种植新植物时改变难度。",
    "All Adjacency Bonuses Stack!": "所有相邻奖励叠加！",
    "Applied Last, Passive Water and Sunlight Absorption^2.": "最后应用，被动水和阳光吸收^2。",
    "Applied Last, Reduces Flower sugar and water thresholds significantly, Manual Absorption^2.": "最后应用，显着降低花糖和水的阈值，手动吸收^2。",
    "Applied Last, Season Bonuses*2, Manual Absorbtion^2, Spread^2.": "最后应用、赛季加成*2、手动吸收^2、传播^2。",
    "Applied Last, Squares Time Boost Effect.": "最后应用，平方时间增强效果。",
    "Applied Last, Starting Roots^2 and Starting Leaves^2.": "最后应用、起始根^2 和起始叶^2。",
    "Applied Last, Sugar Production^2.": "最后应用，糖生产^2。",
    "Are you sure you want to delete your save? This action cannot be undone.": "您确定要删除您的保存吗？ 此操作无法撤消。",
    "Autumn": "秋季",
    "Base Production Rate:": "基础生产率：",
    "Base Water Increase Per Root:": "每个根系增加的基础水：",
    "Basics": "基础",
    "Berry Bush:": "浆果灌木：",
    "Best Plants in Each Category:": "每个类别中的最佳植物：",
    "Best Size Reached": "达到最佳尺寸",
    "Bush Column": "灌木列",
    "Calcium (Fern)": "钙（蕨类植物）",
    "Calcium:": "钙：",
    "Close": "关闭",
    "Column Bonuses": "列奖励",
    "Column Bonuses Can Only Be Applied Once!": "列奖励只能应用一次！",
    "Column Bonuses:": "列奖励：",
    "Column must still be filled with the plant, and only one column bonus per plant can be active.": "列仍必须充满植物，并且每株植物只能激活一列奖励。",
    "Confirm Delete": "确认删除",
    "Detailed Report:": "详细报告：",
    "DNA unlocked with the Time Vine are PERMANENT.": "用时间藤解锁的 DNA 是永久的。",
    "Export to Textbox": "导出到文本框",
    "Fern Column": "蕨类列",
    "Fern:": "蕨类：",
    "Fulvic (Grass)": "黄腐酸（草）",
    "Fulvic:": "黄腐酸：",
    "Game Basics:": "游戏基础知识：",
    "GAME PAUSED!": "游戏暂停！",
    "Grass Column": "草列",
    "Grass:": "草：",
    "Import from Textbox": "从文本框导入",
    "Import/Export State": "导入/导出",
    "Leaves Sunlight Increase:": "叶子阳光增加：",
    "Map Bonuses:": "地图奖励：",
    "Moss Column": "苔藓列",
    "Moss:": "苔藓：",
    "Most Sugar Created": "产生最多的糖",
    "Most Sunlight Absorbed": "吸收最多的阳光",
    "Most Water Absorbed": "吸水最多",
    "Net Sunlight:": "净阳光：",
    "Net Water:": "净水量：",
    "Planted:": "种植：",
    "Replaced:": "替换：",
    "Resources": "资源",
    "Score": "分数",
    "Silica (Succulent)": "二氧化硅（肉质）",
    "Silica:": "二氧化硅：",
    "Size Reached:": "达到的尺寸：",
    "Stored Sunlight:": "储存的阳光：",
    "Stored Water:": "储存的水：",
    "Strategies": "策略",
    "Strategies:": "策略：",
    "Succulent Column": "多肉列",
    "Succulent:": "多肉植物：",
    "Sugar:": "糖：",
    "Sugar.": "糖。",
    "Sugars Being Produced/cycle: ": "正在生产/循环的糖：",
    "Sunlight After Ladybug Tax:": "瓢虫税后的阳光：",
    "Sunlight Increase expected for Autumn Effect:": "秋季效应预计阳光增加：",
    "Sunlight Increase expected for Spring Effect:": "春季效应预计阳光增加：",
    "Sunlight Increase expected for Summer Effect:": "夏季效应预计阳光增加：",
    "Sunlight Increase expected for Winter Effect:": "预计冬季效果的阳光增加：",
    "Sunlight Increase with Current Seasonal Effect:": "阳光随着当前季节的影响而增加：",
    "Sunlight or": "阳光或",
    "Sunlight Used Producing Sugar:": "利用阳光生产糖：",
    "Sunlight, 10k": "阳光，10k",
    "Sunlight:": "阳光：",
    "Table of Contents": "目录",
    "Tannins (Moss)": "单宁（苔藓）",
    "Tannins:": "单宁：",
    "The Time Vine:": "时间藤：",
    "Time Boosting is important, meaning the Fern and Succulent are important.": "时间提升很重要，这意味着蕨类植物和多肉植物也很重要。",
    "Time Resource Progress": "时间资源进度",
    "Time Vine": "时间藤",
    "Time Vine Column": "时间藤列",
    "Total Sugar Created:": "产生的总糖：",
    "Total Sunlight Absorbed:": "吸收的总阳光：",
    "Total Water Absorbed:": "总吸水量：",
    "Unpause": "取消暂停",
    "Water After Ladybug Tax:": "瓢虫税后的水：",
    "Water Decreased All Leaves:": "所有叶子的水分减少：",
    "Water Decreased Per Leaf:": "每片叶子的水分减少：",
    "Water Increase expected for Autumn Effect:": "秋季预计增水效果：",
    "Water Increase expected for Spring Effect:": "春季效应预计水量增加：",
    "Water Increase expected for Summer Effect:": "预计夏季水量增加的影响：",
    "Water Increase expected for Winter Effect:": "预计冬季影响的水量增加：",
    "Water Increase with Current Seasonal Effect:": "当前季节影响水量增加：",
    "Water Increase without Seasonal Effect:": "水量增加不受季节影响：",
    "Water Used Producing Sugar:": "制糖用水：",
    "Water, and 10k": "水和10k",
    "Water, but it can produce": "水，但它可以产生",
    "Water:": "水：",
    "You lost a leaf!": "你失去了一片叶子！",
    "/s": "/秒",
    "/s per Flower": "/秒 每朵花",
    "Flowers consume twice as much sugar and water but mature twice as fast": "花朵消耗两倍的糖和水，但成熟速度却快两倍",
    "Flowers:": "花朵：",
    "Turbo Flowers": "涡轮花",
    "Unlock the Map (All Species)": "解锁地图（所有物种）",
    "Unlock the map.": "解锁地图。",
    "You are a Berry Bush": "你是一片浆果灌木",
    "Winter": "冬季",
    "Sell": "出售",
    "You Have Aphids!": "你身上有蚜虫！",
    "Confirm Import": "确认导入",
    "Importing will overwrite your current state. Are you sure?": "导入将覆盖您当前的状态。 你确定吗？",
    "% of your produced sunlight and water into Pheromones for 7 days...": "7 天后，您产生的阳光和水转化为信息素的百分比...",
    "Activate Protection": "激活保护",
    "Decline Protection": "拒绝保护",
    "It looks like you've managed to attract some Aphids. They are consuming": "看起来您已经成功吸引了一些蚜虫。 他们正在消费",
    "Sugar per second. We can offer you protection if you want to convert": "每秒糖数。 如果您想转换，我们可以为您提供保护",
    "The Lady Bug": "瓢虫",
    "Boost:": "提升:",
    "No plants available for this category.": "此类别没有可用的植物。",
    "Watch your Root Rot!": "注意你的根部腐烂！",
    " (Increase base sugar production by 50%)": "（基础糖产量增加50%）",
    " (Increase manual sunlight absorption by 50%)": "  （手动阳光吸收增加50%）",
    " (Increase manual water absorption by 50%)": "  （手动吸水率增加50%）",
    " (Increase passive sunlight absorption efficiency by 20%)": "  （被动阳光吸收效率提高20%）",
    " (Increase passive water absorption efficiency by 20%)": "  （被动吸水效率提高20%）",
    " (Reduce the base sunlight to sugar ratio by 10%)": "  （将基础阳光与糖的比例减少10%）",
    " (Reduce the base water to sugar ratio by 10%)": "  (基础水与糖的比例减少10%)",
    " Tier 2 (Increase base sugar production by 100%)": "  2 级（基础糖产量增加 100%）",
    "Auto grows 100 more roots or leaves per cycle, for the same sugar.": "对于相同的糖分，每个周期自动会多生长 100 个根或叶。",
    "Auto grows 1000 more roots or leaves per cycle, for the same sugar.": "对于相同的糖分，自动在每个周期中多生长 1000 个根或叶。",
    "Auto grows 10000 more roots or leaves per cycle, for the same sugar.": "对于相同的糖，自动在每个周期中多生长 10000 个根或叶。",
    "Burn the forest to the ground to rejuvenate the soil. (Reset Leaves Needed for DNA)": "将森林烧毁，使土壤恢复活力。 （DNA 需要重置叶子）",
    "Growth Toggle (All Species)": "生长切换（所有物种）",
    "Option to toggle auto growth on/off.": "打开/关闭自动增长的选项。",
    "Reduce the cost of auto root growth from 5x to 2x": "将自动根生长的成本从 5 倍降低到 2 倍",
    "Rhizomes": "根茎",
    "Stop": "停止",
    "The Flame": "火焰",
    "Wildfire": "野火",
    "You are a Colony of Grass": "你是一丛野草",
    "Agave Sugar (All Species)": "龙舌兰糖（所有物种）",
    "Darker Desert Night": "更黑暗的沙漠之夜",
    "Deeper Desert Rain": "更深的沙漠雨",
    "Desert Night": "沙漠之夜",
    "Desert Rain": "沙漠雨",
    "Grow Needles:": "种植针：",
    "Leaves:": "树叶：",
    "Needles protect 100% more water": "针可保护 100% 以上的水",
    "Needles protect 50% more water": "针可保护 50% 以上的水",
    "Needles protect twice as much water": "针可以保护两倍的水",
    "Needles protecting:": "针头防护：",
    "Rabbit Immunity": "兔子免疫",
    "Reset Sugar needed for DNA": "重置 DNA 所需的糖",
    "Reset the amount of sugar needed to gain DNA progress.": "重置获得 DNA 进展所需的糖量。",
    "Succulents are immune to rabbits": "多肉植物对兔子免疫",
    "Sugar production 10X for non-Succulent plants.": "非多肉植物的糖产量提高 10 倍。",
    "Time travel in the Darkness of the Desert. (Around 150 minutes)": "在沙漠的黑暗中进行时间旅行。 （约150分钟）",
    "Time travel in the Darkness of the Desert. (Around 3 minutes)": "在沙漠的黑暗中进行时间旅行。 （约3分钟）",
    "Time travel in the intense Desert Rains. (Around 150 minutes)": "在强烈的沙漠雨中进行时间旅行。 （约150分钟）",
    "Time travel in the intense Desert Rains. (Around 3 minutes)": "在强烈的沙漠雨中进行时间旅行。 （约3分钟）",
    "Water Drop": "水滴",
    "Water Flood": "水淹",
    "Water Splash": "水溅",
    "You are a Succulent": "你是一颗多肉植物",
    "Absorbent Leaves (All Species)": "吸收性叶子（所有物种）",
    "Bromeliad": "凤梨科",
    "Doubles the amount of sunlight absorbed by Moss": "苔藓吸收的阳光量加倍",
    "Grow:": "生长：",
    "Increase base sugar production by 200%": "基础糖产量增加 200%",
    "Increase base sugar production by 300%": "基础糖产量增加 300%",
    "Leaves are water neutral and no longer lost due to dehydration.": "叶子是水中性的，不再因脱水而损失。",
    "Lichen Co-Op": "地衣合作社",
    "No inventory available for Moss. Check back when you've unlocked the Lichen trait!": "莫斯没有可用库存。 解锁地衣特质后请回来查看！",
    "Unlocks the Lichen Store": "解锁地衣商店",
    "You are a clump of Moss": "你是一块苔藓",
    " (Flowers now give 2 more DNA when they mature)": "（花朵成熟时现在会多出 2 个 DNA）",
    " Tier 2 (Increase passive water absorption efficiency by 40%)": " 2 级（被动吸水效率提高40%）",
    "Grow Leaves and Roots": "长叶子和根",
    "Grow Max Leaves & Roots": "长最大叶子和根",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'I',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Root Hairs": "根毛",
    "Heliotropism": "趋日性",
    "Trichomes": "表皮毛",
    "Stomatal Regulation": "气孔调节",
    "Aquaporins": "水通道蛋白",
    "Cam Pathway": "代谢途径",
    "Extra Chlorophyll": "额外叶绿素",
    "Thermophilic": "喜热",
    "Current Version:": "当前版本：",
    "Flower DNA": "鲜花 DNA",
    "Needle Protection": "针头保护",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    " Tier 2": " 2 级",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)d ([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^\-([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Flowers now give (.+) more DNA when they mature$/, '花朵成熟时现在会多提供 $1 DNA'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^([\d\.,]+) water.$/, '$1 水。'],
    [/^Year ([\d\.,]+)\-Spring\-([\d\.,]+)$/, '年 $1\-春\-$2'],
    [/^Spread ([\d\.,]+)$/, '蔓延 $1'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);